# Handeling date and time

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Database.csv",)
df=df[["Date","Time"]]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    23412 non-null  object
 1   Time    23412 non-null  object
dtypes: object(2)
memory usage: 365.9+ KB

In [4]:
# converting the string date column to date time column
df['Date'] = pd.to_datetime(df['Date'], utc=True, errors='coerce')

In [5]:
df.columns

Index(['Date', 'Time'], dtype='object')

In [6]:
df

                           Date      Time
0     1965-01-02 00:00:00+00:00  13:44:18
1     1965-01-04 00:00:00+00:00  11:29:49
2     1965-01-05 00:00:00+00:00  18:05:58
3     1965-01-08 00:00:00+00:00  18:49:43
4     1965-01-09 00:00:00+00:00  13:32:50
...                         ...       ...
23407 2016-12-28 00:00:00+00:00  08:22:12
23408 2016-12-28 00:00:00+00:00  09:13:47
23409 2016-12-28 00:00:00+00:00  12:38:51
23410 2016-12-29 00:00:00+00:00  22:30:19
23411 2016-12-30 00:00:00+00:00  20:08:28

[23412 rows x 2 columns]

## Extract Year

In [7]:
df['date_year'] = df['Date'].dt.year
df

                           Date      Time  date_year
0     1965-01-02 00:00:00+00:00  13:44:18     1965.0
1     1965-01-04 00:00:00+00:00  11:29:49     1965.0
2     1965-01-05 00:00:00+00:00  18:05:58     1965.0
3     1965-01-08 00:00:00+00:00  18:49:43     1965.0
4     1965-01-09 00:00:00+00:00  13:32:50     1965.0
...                         ...       ...        ...
23407 2016-12-28 00:00:00+00:00  08:22:12     2016.0
23408 2016-12-28 00:00:00+00:00  09:13:47     2016.0
23409 2016-12-28 00:00:00+00:00  12:38:51     2016.0
23410 2016-12-29 00:00:00+00:00  22:30:19     2016.0
23411 2016-12-30 00:00:00+00:00  20:08:28     2016.0

[23412 rows x 3 columns]

## Extract Month

In [8]:
df['date_month'] = df['Date'].dt.month
df

                           Date      Time  date_year  date_month
0     1965-01-02 00:00:00+00:00  13:44:18     1965.0         1.0
1     1965-01-04 00:00:00+00:00  11:29:49     1965.0         1.0
2     1965-01-05 00:00:00+00:00  18:05:58     1965.0         1.0
3     1965-01-08 00:00:00+00:00  18:49:43     1965.0         1.0
4     1965-01-09 00:00:00+00:00  13:32:50     1965.0         1.0
...                         ...       ...        ...         ...
23407 2016-12-28 00:00:00+00:00  08:22:12     2016.0        12.0
23408 2016-12-28 00:00:00+00:00  09:13:47     2016.0        12.0
23409 2016-12-28 00:00:00+00:00  12:38:51     2016.0        12.0
23410 2016-12-29 00:00:00+00:00  22:30:19     2016.0        12.0
23411 2016-12-30 00:00:00+00:00  20:08:28     2016.0        12.0

[23412 rows x 4 columns]

In [9]:
#With names of the months

df['date_month_name'] = df['Date'].dt.month_name()
df

,Date,Time,date_year,date_month,date_month_name
0,1965-01-02 00:00:00+00:00,13:44:18,1965.0,1.0,January
1,1965-01-04 00:00:00+00:00,11:29:49,1965.0,1.0,January
2,1965-01-05 00:00:00+00:00,18:05:58,1965.0,1.0,January
3,1965-01-08 00:00:00+00:00,18:49:43,1965.0,1.0,January
4,1965-01-09 00:00:00+00:00,13:32:50,1965.0,1.0,January
...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,08:22:12,2016.0,12.0,December
23408,2016-12-28 00:00:00+00:00,09:13:47,2016.0,12.0,December
23409,2016-12-28 00:00:00+00:00,12:38:51,2016.0,12.0,December
23410,2016-12-29 00:00:00+00:00,22:30:19,2016.0,12.0,December
23411,2016-12-30 00:00:00+00:00,20:08:28,2016.0,12.0,December

## Extract Days

In [11]:
df['date_days'] = df['Date'].dt.day
df

,Date,Time,date_year,date_month,date_month_name,date_days
0,1965-01-02 00:00:00+00:00,13:44:18,1965.0,1.0,January,2.0
1,1965-01-04 00:00:00+00:00,11:29:49,1965.0,1.0,January,4.0
2,1965-01-05 00:00:00+00:00,18:05:58,1965.0,1.0,January,5.0
3,1965-01-08 00:00:00+00:00,18:49:43,1965.0,1.0,January,8.0
4,1965-01-09 00:00:00+00:00,13:32:50,1965.0,1.0,January,9.0
...,...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,08:22:12,2016.0,12.0,December,28.0
23408,2016-12-28 00:00:00+00:00,09:13:47,2016.0,12.0,December,28.0
23409,2016-12-28 00:00:00+00:00,12:38:51,2016.0,12.0,December,28.0
23410,2016-12-29 00:00:00+00:00,22:30:19,2016.0,12.0,December,29.0
23411,2016-12-30 00:00:00+00:00,20:08:28,2016.0,12.0,December,30.0

## Extract Day of week

In [12]:
df['date_DayOfWeek'] = df['Date'].dt.dayofweek
df

,Date,Time,date_year,date_month,date_month_name,date_days,date_DayOfWeek
0,1965-01-02 00:00:00+00:00,13:44:18,1965.0,1.0,January,2.0,5.0
1,1965-01-04 00:00:00+00:00,11:29:49,1965.0,1.0,January,4.0,0.0
2,1965-01-05 00:00:00+00:00,18:05:58,1965.0,1.0,January,5.0,1.0
3,1965-01-08 00:00:00+00:00,18:49:43,1965.0,1.0,January,8.0,4.0
4,1965-01-09 00:00:00+00:00,13:32:50,1965.0,1.0,January,9.0,5.0
...,...,...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,08:22:12,2016.0,12.0,December,28.0,2.0
23408,2016-12-28 00:00:00+00:00,09:13:47,2016.0,12.0,December,28.0,2.0
23409,2016-12-28 00:00:00+00:00,12:38:51,2016.0,12.0,December,28.0,2.0
23410,2016-12-29 00:00:00+00:00,22:30:19,2016.0,12.0,December,29.0,3.0
23411,2016-12-30 00:00:00+00:00,20:08:28,2016.0,12.0,December,30.0,4.0

## Extract Day of week -name

In [14]:
df['date_DayOfWeek_name'] = df['Date'].dt.day_name()
df

,Date,Time,date_year,date_month,date_month_name,date_days,date_DayOfWeek,date_DayOfWeek_name
0,1965-01-02 00:00:00+00:00,13:44:18,1965.0,1.0,January,2.0,5.0,Saturday
1,1965-01-04 00:00:00+00:00,11:29:49,1965.0,1.0,January,4.0,0.0,Monday
2,1965-01-05 00:00:00+00:00,18:05:58,1965.0,1.0,January,5.0,1.0,Tuesday
3,1965-01-08 00:00:00+00:00,18:49:43,1965.0,1.0,January,8.0,4.0,Friday
4,1965-01-09 00:00:00+00:00,13:32:50,1965.0,1.0,January,9.0,5.0,Saturday
...,...,...,...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,08:22:12,2016.0,12.0,December,28.0,2.0,Wednesday
23408,2016-12-28 00:00:00+00:00,09:13:47,2016.0,12.0,December,28.0,2.0,Wednesday
23409,2016-12-28 00:00:00+00:00,12:38:51,2016.0,12.0,December,28.0,2.0,Wednesday
23410,2016-12-29 00:00:00+00:00,22:30:19,2016.0,12.0,December,29.0,3.0,Thursday
23411,2016-12-30 00:00:00+00:00,20:08:28,2016.0,12.0,December,30.0,4.0,Friday

## Is it the weekend

In [19]:
df['date_is_weekend'] = np.where(df['date_DayOfWeek_name'].isin(['Sunday', 'Saturday']), 1, 0)
df

,Date,Time,date_year,date_month,date_month_name,date_days,date_DayOfWeek,date_DayOfWeek_name,date_is_weekend
0,1965-01-02 00:00:00+00:00,13:44:18,1965.0,1.0,January,2.0,5.0,Saturday,1
1,1965-01-04 00:00:00+00:00,11:29:49,1965.0,1.0,January,4.0,0.0,Monday,0
2,1965-01-05 00:00:00+00:00,18:05:58,1965.0,1.0,January,5.0,1.0,Tuesday,0
3,1965-01-08 00:00:00+00:00,18:49:43,1965.0,1.0,January,8.0,4.0,Friday,0
4,1965-01-09 00:00:00+00:00,13:32:50,1965.0,1.0,January,9.0,5.0,Saturday,1
...,...,...,...,...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,08:22:12,2016.0,12.0,December,28.0,2.0,Wednesday,0
23408,2016-12-28 00:00:00+00:00,09:13:47,2016.0,12.0,December,28.0,2.0,Wednesday,0
23409,2016-12-28 00:00:00+00:00,12:38:51,2016.0,12.0,December,28.0,2.0,Wednesday,0
23410,2016-12-29 00:00:00+00:00,22:30:19,2016.0,12.0,December,29.0,3.0,Thursday,0
23411,2016-12-30 00:00:00+00:00,20:08:28,2016.0,12.0,December,30.0,4.0,Friday,0

## Extract week of the year

In [21]:
df['date_week'] = df['Date'].dt.isocalendar().week
df

,Date,Time,date_year,date_month,date_month_name,date_days,date_DayOfWeek,date_DayOfWeek_name,date_is_weekend,date_week
0,1965-01-02 00:00:00+00:00,13:44:18,1965.0,1.0,January,2.0,5.0,Saturday,1,53
1,1965-01-04 00:00:00+00:00,11:29:49,1965.0,1.0,January,4.0,0.0,Monday,0,1
2,1965-01-05 00:00:00+00:00,18:05:58,1965.0,1.0,January,5.0,1.0,Tuesday,0,1
3,1965-01-08 00:00:00+00:00,18:49:43,1965.0,1.0,January,8.0,4.0,Friday,0,1
4,1965-01-09 00:00:00+00:00,13:32:50,1965.0,1.0,January,9.0,5.0,Saturday,1,1
...,...,...,...,...,...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,08:22:12,2016.0,12.0,December,28.0,2.0,Wednesday,0,52
23408,2016-12-28 00:00:00+00:00,09:13:47,2016.0,12.0,December,28.0,2.0,Wednesday,0,52
23409,2016-12-28 00:00:00+00:00,12:38:51,2016.0,12.0,December,28.0,2.0,Wednesday,0,52
23410,2016-12-29 00:00:00+00:00,22:30:19,2016.0,12.0,December,29.0,3.0,Thursday,0,52
23411,2016-12-30 00:00:00+00:00,20:08:28,2016.0,12.0,December,30.0,4.0,Friday,0,52

## Extract Quater

In [25]:
df['date_quarter'] = df['Date'].dt.quarter
df

,Date,Time,date_year,date_month,date_month_name,date_days,date_DayOfWeek,date_DayOfWeek_name,date_is_weekend,date_week,date_quarter
0,1965-01-02 00:00:00+00:00,13:44:18,1965.0,1.0,January,2.0,5.0,Saturday,1,53,1.0
1,1965-01-04 00:00:00+00:00,11:29:49,1965.0,1.0,January,4.0,0.0,Monday,0,1,1.0
2,1965-01-05 00:00:00+00:00,18:05:58,1965.0,1.0,January,5.0,1.0,Tuesday,0,1,1.0
3,1965-01-08 00:00:00+00:00,18:49:43,1965.0,1.0,January,8.0,4.0,Friday,0,1,1.0
4,1965-01-09 00:00:00+00:00,13:32:50,1965.0,1.0,January,9.0,5.0,Saturday,1,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,08:22:12,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0
23408,2016-12-28 00:00:00+00:00,09:13:47,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0
23409,2016-12-28 00:00:00+00:00,12:38:51,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0
23410,2016-12-29 00:00:00+00:00,22:30:19,2016.0,12.0,December,29.0,3.0,Thursday,0,52,4.0
23411,2016-12-30 00:00:00+00:00,20:08:28,2016.0,12.0,December,30.0,4.0,Friday,0,52,4.0

## Extract tome elapsed between dates

In [28]:
import datetime
today = datetime.datetime.today()
today # Todays data stamp

datetime.datetime(2026, 3, 29, 11, 38, 8, 237386)

In [30]:
today = pd.Timestamp.now(tz='UTC')
today-df["Date"]

0       22366 days 06:11:04.995337
1       22364 days 06:11:04.995337
2       22363 days 06:11:04.995337
3       22360 days 06:11:04.995337
4       22359 days 06:11:04.995337
                   ...
23407    3378 days 06:11:04.995337
23408    3378 days 06:11:04.995337
23409    3378 days 06:11:04.995337
23410    3377 days 06:11:04.995337
23411    3376 days 06:11:04.995337
Name: Date, Length: 23412, dtype: timedelta64[ns]

In [33]:
(today-df["Date"]).dt.days

0        22366.0
1        22364.0
2        22363.0
3        22360.0
4        22359.0
          ...
23407     3378.0
23408     3378.0
23409     3378.0
23410     3377.0
23411     3376.0
Name: Date, Length: 23412, dtype: float64

In [39]:
# years passed
df['years_diff'] =(today - df['Date']).dt.days / 365
df

0        61.276712
1        61.271233
2        61.268493
3        61.260274
4        61.257534
           ...
23407     9.254795
23408     9.254795
23409     9.254795
23410     9.252055
23411     9.249315
Name: Date, Length: 23412, dtype: float64

In [42]:
#months passed
df['months_diff'] =(today - df['Date']).dt.days / 30
df

,Date,Time,date_year,date_month,date_month_name,date_days,date_DayOfWeek,date_DayOfWeek_name,date_is_weekend,date_week,date_quarter,years_diff,months_diff
0,1965-01-02 00:00:00+00:00,13:44:18,1965.0,1.0,January,2.0,5.0,Saturday,1,53,1.0,61.276712,745.533333
1,1965-01-04 00:00:00+00:00,11:29:49,1965.0,1.0,January,4.0,0.0,Monday,0,1,1.0,61.271233,745.466667
2,1965-01-05 00:00:00+00:00,18:05:58,1965.0,1.0,January,5.0,1.0,Tuesday,0,1,1.0,61.268493,745.433333
3,1965-01-08 00:00:00+00:00,18:49:43,1965.0,1.0,January,8.0,4.0,Friday,0,1,1.0,61.260274,745.333333
4,1965-01-09 00:00:00+00:00,13:32:50,1965.0,1.0,January,9.0,5.0,Saturday,1,1,1.0,61.257534,745.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,08:22:12,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0,9.254795,112.600000
23408,2016-12-28 00:00:00+00:00,09:13:47,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0,9.254795,112.600000
23409,2016-12-28 00:00:00+00:00,12:38:51,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0,9.254795,112.600000
23410,2016-12-29 00:00:00+00:00,22:30:19,2016.0,12.0,December,29.0,3.0,Thursday,0,52,4.0,9.252055,112.566667
23411,2016-12-30 00:00:00+00:00,20:08:28,2016.0,12.0,December,30.0,4.0,Friday,0,52,4.0,9.249315,112.533333

## For extract of time

In [49]:
df['Time'] = pd.to_datetime(df['Time'], errors='coerce')

df['hour'] = df['Time'].dt.hour
df['min'] = df['Time'].dt.minute
df['sec'] = df['Time'].dt.second

df

,Date,Time,date_year,date_month,date_month_name,date_days,date_DayOfWeek,date_DayOfWeek_name,date_is_weekend,date_week,date_quarter,years_diff,months_diff,hour,min,sec
0,1965-01-02 00:00:00+00:00,2026-03-29 13:44:18,1965.0,1.0,January,2.0,5.0,Saturday,1,53,1.0,61.276712,745.533333,13.0,44.0,18.0
1,1965-01-04 00:00:00+00:00,2026-03-29 11:29:49,1965.0,1.0,January,4.0,0.0,Monday,0,1,1.0,61.271233,745.466667,11.0,29.0,49.0
2,1965-01-05 00:00:00+00:00,2026-03-29 18:05:58,1965.0,1.0,January,5.0,1.0,Tuesday,0,1,1.0,61.268493,745.433333,18.0,5.0,58.0
3,1965-01-08 00:00:00+00:00,2026-03-29 18:49:43,1965.0,1.0,January,8.0,4.0,Friday,0,1,1.0,61.260274,745.333333,18.0,49.0,43.0
4,1965-01-09 00:00:00+00:00,2026-03-29 13:32:50,1965.0,1.0,January,9.0,5.0,Saturday,1,1,1.0,61.257534,745.300000,13.0,32.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,2016-12-28 00:00:00+00:00,NaT,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0,9.254795,112.600000,NaN,NaN,NaN
23408,2016-12-28 00:00:00+00:00,NaT,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0,9.254795,112.600000,NaN,NaN,NaN
23409,2016-12-28 00:00:00+00:00,NaT,2016.0,12.0,December,28.0,2.0,Wednesday,0,52,4.0,9.254795,112.600000,NaN,NaN,NaN
23410,2016-12-29 00:00:00+00:00,NaT,2016.0,12.0,December,29.0,3.0,Thursday,0,52,4.0,9.252055,112.566667,NaN,NaN,NaN
23411,2016-12-30 00:00:00+00:00,NaT,2016.0,12.0,December,30.0,4.0,Friday,0,52,4.0,9.249315,112.533333,NaN,NaN,NaN