# Mixed Data

## Import of libs

In [2]:
import numpy as np
import pandas as pd

## Working of coustomised dataset

In [3]:
df=pd.read_csv("Untitled 1.csv")
df.head()

  Cabina    Ticket Number  Survived
0     A7   8394/34      5         0
1     S6  94385/23      2         1
2     F7   3434/21      S         1
3    NaN  3452/234      D         1
4     T5  35789/45      F         0

In [5]:
df["Number"].unique()

array(['5', '2', 'S', 'D', 'F', '6', 'X'], dtype=object)

In [8]:
# extract numerical part
df['number_numerical'] = pd.to_numeric(df["Number"],errors='coerce',downcast='integer')

# extract categorical part
df['number_categorical'] = np.where(df['number_numerical'].isnull(),df['Number'],np.nan)

df

  Cabina     Ticket Number  Survived  number_numerical number_categorical
0     A7    8394/34      5         0               5.0                NaN
1     S6   94385/23      2         1               2.0                NaN
2     F7    3434/21      S         1               NaN                  S
3    NaN   3452/234      D         1               NaN                  D
4     T5   35789/45      F         0               NaN                  F
5    NaN  54945/435      6         0               6.0                NaN
6     Y0   59934/45      X         1               NaN                  X

In [9]:
df["Cabina"].unique()

array(['A7', 'S6', 'F7', nan, 'T5', 'Y0'], dtype=object)

In [10]:
df["Ticket"].unique()

array(['8394/34', '94385/23', '3434/21', '3452/234', '35789/45',
       '54945/435', '59934/45'], dtype=object)

In [14]:
df['cabin_num'] = df['Cabina'].str.extract('(\d+)') # captures numerical part
df['cabin_cat'] = df['Cabina'].str[0] # captures the first letter

df

,Cabina,Ticket,Number,Survived,number_numerical,number_categorical,cabin_num,cabin_cat
0,A7,8394/34,5,0,5.0,NaN,7,A
1,S6,94385/23,2,1,2.0,NaN,6,S
2,F7,3434/21,S,1,NaN,S,7,F
3,NaN,3452/234,D,1,NaN,D,NaN,NaN
4,T5,35789/45,F,0,NaN,F,5,T
5,NaN,54945/435,6,0,6.0,NaN,NaN,NaN
6,Y0,59934/45,X,1,NaN,X,0,Y

In [15]:
# extract the last bit of ticket as number
df['ticket_num'] = df['Ticket'].apply(lambda s: s.split()[-1])
df['ticket_num'] = pd.to_numeric(df['ticket_num'],
                                errors='coerce',
                                downcast='integer')

# extract the first part of ticket as category
df['ticket_cat'] = df['Ticket'].apply(lambda s: s.split()[0])
df['ticket_cat'] = np.where(df['ticket_cat'].str.isdigit(), np.nan,
                            df['ticket_cat'])

df.head(20)

,Cabina,Ticket,Number,Survived,number_numerical,number_categorical,cabin_num,cabin_cat,ticket_num,ticket_cat
0,A7,8394/34,5,0,5.0,NaN,7,A,NaN,8394/34
1,S6,94385/23,2,1,2.0,NaN,6,S,NaN,94385/23
2,F7,3434/21,S,1,NaN,S,7,F,NaN,3434/21
3,NaN,3452/234,D,1,NaN,D,NaN,NaN,NaN,3452/234
4,T5,35789/45,F,0,NaN,F,5,T,NaN,35789/45
5,NaN,54945/435,6,0,6.0,NaN,NaN,NaN,NaN,54945/435
6,Y0,59934/45,X,1,NaN,X,0,Y,NaN,59934/45